/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudentListRouteImport } from './routes/student-list'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin-referrals'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin-students'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as AuthenticatedCounselorRouteImport } from './routes/_authenticated/counselor'
import { Route as AuthenticatedCounselorsRouteImport } from './routes/_authenticated/counselors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedMyGradesRouteImport } from './routes/_authenticated/my-grades'
import { Route as AuthenticatedMyReferralsRouteImport } from './routes/_authenticated/my-referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListRoute = StudentListRouteImport.update({
  id: '/student-list',
  path: '/student-list',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/admin-referrals',
    path: '/admin-referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin-students',
    path: '/admin-students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounselorRoute = AuthenticatedCounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounselorsRoute = AuthenticatedCounselorsRouteImport.update({
  id: '/counselors',
  path: '/counselors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyGradesRoute = AuthenticatedMyGradesRouteImport.update({
  id: '/my-grades',
  path: '/my-grades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyReferralsRoute =
  AuthenticatedMyReferralsRouteImport.update({
    id: '/my-referrals',
    path: '/my-referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student-list': typeof StudentListRoute
  '/students': typeof StudentsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin-students': typeof AuthenticatedAdminStudentsRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/counselor': typeof AuthenticatedCounselorRoute
  '/counselors': typeof AuthenticatedCounselorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/my-grades': typeof AuthenticatedMyGradesRoute
  '/my-referrals': typeof AuthenticatedMyReferralsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/student': typeof AuthenticatedStudentRoute
  '/trends': typeof AuthenticatedTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student-list': typeof StudentListRoute
  '/students': typeof StudentsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin-students': typeof AuthenticatedAdminStudentsRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/counselor': typeof AuthenticatedCounselorRoute
  '/counselors': typeof AuthenticatedCounselorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/my-grades': typeof AuthenticatedMyGradesRoute
  '/my-referrals': typeof AuthenticatedMyReferralsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/student': typeof AuthenticatedStudentRoute
  '/trends': typeof AuthenticatedTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/student-list': typeof StudentListRoute
  '/students': typeof StudentsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin-students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/counselor': typeof AuthenticatedCounselorRoute
  '/_authenticated/counselors': typeof AuthenticatedCounselorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/my-grades': typeof AuthenticatedMyGradesRoute
  '/_authenticated/my-referrals': typeof AuthenticatedMyReferralsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/student-list'
    | '/students'
    | '/admin'
    | '/admin-referrals'
    | '/admin-students'
    | '/admin-tools'
    | '/counselor'
    | '/counselors'
    | '/dashboard'
    | '/leaderboard'
    | '/my-grades'
    | '/my-referrals'
    | '/profile'
    | '/student'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/student-list'
    | '/students'
    | '/admin'
    | '/admin-referrals'
    | '/admin-students'
    | '/admin-tools'
    | '/counselor'
    | '/counselors'
    | '/dashboard'
    | '/leaderboard'
    | '/my-grades'
    | '/my-referrals'
    | '/profile'
    | '/student'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/student-list'
    | '/students'
    | '/_authenticated/admin'
    | '/_authenticated/admin-referrals'
    | '/_authenticated/admin-students'
    | '/_authenticated/admin-tools'
    | '/_authenticated/counselor'
    | '/_authenticated/counselors'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/my-grades'
    | '/_authenticated/my-referrals'
    | '/_authenticated/profile'
    | '/_authenticated/student'
    | '/_authenticated/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudentListRoute: typeof StudentListRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list': {
      id: '/student-list'
      path: '/student-list'
      fullPath: '/student-list'
      preLoaderRoute: typeof StudentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-referrals': {
      id: '/_authenticated/admin-referrals'
      path: '/admin-referrals'
      fullPath: '/admin-referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-students': {
      id: '/_authenticated/admin-students'
      path: '/admin-students'
      fullPath: '/admin-students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counselor': {
      id: '/_authenticated/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof AuthenticatedCounselorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counselors': {
      id: '/_authenticated/counselors'
      path: '/counselors'
      fullPath: '/counselors'
      preLoaderRoute: typeof AuthenticatedCounselorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-grades': {
      id: '/_authenticated/my-grades'
      path: '/my-grades'
      fullPath: '/my-grades'
      preLoaderRoute: typeof AuthenticatedMyGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-referrals': {
      id: '/_authenticated/my-referrals'
      path: '/my-referrals'
      fullPath: '/my-referrals'
      preLoaderRoute: typeof AuthenticatedMyReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedCounselorRoute: typeof AuthenticatedCounselorRoute
  AuthenticatedCounselorsRoute: typeof AuthenticatedCounselorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMyGradesRoute: typeof AuthenticatedMyGradesRoute
  AuthenticatedMyReferralsRoute: typeof AuthenticatedMyReferralsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedCounselorRoute: AuthenticatedCounselorRoute,
  AuthenticatedCounselorsRoute: AuthenticatedCounselorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMyGradesRoute: AuthenticatedMyGradesRoute,
  AuthenticatedMyReferralsRoute: AuthenticatedMyReferralsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StudentListRoute: StudentListRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
